### PR TITLE
Add Litestar framework

### PR DESCRIPTION
**Pull request by i404788**
**Checklist**

- [x] This project is explicitly related to ASGI.
- [x] The new list entry contains a project name, URL and description.

**What is this project?**

Starlite,  a light, opinionated and flexible ASGI API framework built on top of pydantic and Starlette.

https://starlite-api.github.io/starlite/

**Do you know about other similar projects?**

Yes, similar to FastAPI (both Starlette + Pydantic with OpenAPI endpoints), but afaik not related in structure/code.

**If so, how is this one different?**

Starlite is more lightweight, and (in my testing) faster due to the use of orjson.

---

_Anyone who agrees with this pull request can add a 👍._

### CODE REVIEW

**Review by Swannbm — APPROVED** [review]

**Comment by euri10** [comment]
Actually this is now Litestar (https://litestar.dev/) and it's an amazing framework, very-well tested, packed with many interesting goodies, easily extendible and pluggable, you should definitely add it @florimondmanca ;) 

what's the trigger for you to make it happen ?

**Comment by florimondmanca** [comment]
Nothing in particular — I actually thought we had already added Litestar to the list somehow!

I’m away and can’t commit code myself. @i404788 if you’re still getting messages from this thread, would you be up for the Starlite -> Litestar update?

Otherwise somebody can open a new updated PR that would override this one.

**Comment by i404788** [comment]
@florimondmanca I'll update it, I still actively use litestar

**Comment by i404788** [comment]
@florimondmanca I've updated it, the actual project has changed a lot (it's not based on pydantic & starlette anymore, and there have been many more features) since so I've had to update the description significantly, let me know if it's alright.

**Review by florimondmanca — APPROVED** [review]
Looking great, thank you!

**Pull request merged**
